(function(){var g=!0,h=null,i=!1;document.getElementsByClassName||(document.getElementsByClassName=function(b){var a=b.split(" "),b=[],c=document.getElementsByTagName("*"),d,e=[];d=0;for(var f=a.length;d<f;d++)b.push(RegExp("(^|\\s)"+a[d]+"(\\s|$)"));for(var f=0,t=c.length;f<t;f++){a=c[f];d=i;for(var u=0,F=b.length;u<F&&!(d=b[u].test(a.className),!d);u+=1);d&&e.push(a)}return e});window.highedweb=window.highedweb||{};
function j(b,a,c){b.addEventListener?b.addEventListener(a,c,i):b.attachEvent("on"+a,function(){c.call(window.event.srcElement,window.event)})}window.highedweb.addEvent=j;var m=i,n=[],o=window;function p(){if(!document.loaded&&(document.loaded=g,!m)){m=g;for(var b=0;b<n.length;b++)n[b]()}}var q=o.document,r=o.navigator.userAgent.toLowerCase(),s=parseFloat(r.match(/.+(?:rv|it|ml|ra|ie)[\/: ]([\d.]+)/)[1]);
if(/webkit\//.test(r)&&525.13>s)(function(){/complete|loaded/.test(q.readyState)?p():window.setTimeout(arguments.callee,10)})();else if(/msie/.test(r)&&!o.opera)q.attachEvent("onreadystatechange",function(b){"complete"==q.readyState&&(q.detachEvent("on"+b.type,arguments.callee),p())}),o==top&&function(){try{q.documentElement.doScroll("left")}catch(b){window.setTimeout(arguments.callee,10);return}p()}();else if(q.addEventListener&&/opera\//.test(r)&&9<s||/gecko\//.test(r)&&1.8<=s||/khtml\//.test(r)&&
4<=s||/webkit\//.test(r)&&525.13<=s)q.addEventListener("DOMContentLoaded",function(b){q.removeEventListener("DOMContentLoaded",arguments.callee,i);p()},i);else{var v=o.onload;o.onload=function(b){p();"function"==typeof v&&v(b||o.event)}}function w(b){m?b():n.push(b)}window.highedweb.addLoadEvent=w;function x(b,a){this.a=b;this.loaded=a}x.prototype.loaded=i;x.prototype.a=h;var y={};
function z(b,a){A.IE&&0>B(C,"9.0")?j(b,"readystatechange",function(){if("loaded"==this.readyState||"complete"==this.readyState)y[b.src]&&(y[b.src].loaded=g),a&&a.call(this)}):j(b,"load",function(){y[b.src]&&(y[b.src].loaded=g);a&&a.call(this)})}
function D(b,a,c,d){var e=h,f=h;if(!c){if(y[b]){d&&(y[b].loaded?d.call(y[b].a):z(y[b].a,d));return}e=document.getElementsByTagName("script");for(c=0;c<e.length;c++)if(e[c].src==b){y[b]=new x(e[c],g);d&&d.call(e[c]);return}}f=document.createElement("script");f.type="text/javascript";f.src=b;a&&(f.async=g);y[b]=new x(f,i);z(f,d);e||(e=document.getElementsByTagName("script"));e[0].parentNode.insertBefore(f,e[0])}window.highedweb.requireScript=D;var E={};
window.highedweb.requireLink=function(b){if(!E[b]){var a=document.getElementsByTagName("head");if(a){for(var a=a[0],c=a.getElementsByTagName("link"),d=0;d<c.length;d++)if(c[d].href==b){E[b]=g;return}d=document.createElement("link");d.rel="stylesheet";d.href=b;d.type="text/css";d.media="all";c?a.insertBefore(d,c[0]):a.appendChild(d)}}};
window.highedweb.outputLastModifiedDate=function(){if(document.lastModified){var b,a,c;b=i;c=new Date(document.lastModified);if(c.getTime()+5E3>=(new Date).getTime())document.write("unknown");else{var d=c.getDate(),e=c.getFullYear();switch(c.getMonth()){case 0:a="January";break;case 1:a="February";break;case 2:a="March";break;case 3:a="April";break;case 4:a="May";break;case 5:a="June";break;case 6:a="July";break;case 7:a="August";break;case 8:a="September";break;case 9:a="October";break;case 10:a=
"November";break;case 11:a="December";break;default:b=g}document.write(b?"unknown":a+(" "+d+", "+e))}}else document.write("unknown")};window.highedweb.outputDocumentLocation=function(){document.write(document.location.protocol+"//"+document.location.host);""!=document.location.port&&document.write(":"+document.location.port);document.write(document.location.pathname+document.location.search)};var A={OPERA:i,IE:i,GECKO:i,WEBKIT:i,MOBILE:i};A.OPERA=0==navigator.userAgent.indexOf("Opera");
A.IE=!A.OPERA&&-1!=navigator.userAgent.indexOf("MSIE");A.WEBKIT=!A.OPERA&&-1!=navigator.userAgent.indexOf("WebKit");A.MOBILE=A.WEBKIT&&-1!=navigator.userAgent.indexOf("Mobile");A.GECKO=!A.OPERA&&!A.WEBKIT&&"Gecko"==navigator.product;var C="",G,H;
if(A.OPERA)C="function"==typeof window.opera.version?window.opera.version():window.opera.version;else if(A.GECKO?G=/rv\:([^\);]+)(\)|;)/:A.IE?G=/MSIE\s+([^\);]+)(\)|;)/:A.WEBKIT&&(G=/WebKit\/(\S+)/),G&&(C=(H=G.exec(navigator.userAgent))?H[1]:""),A.IE&&(G=/Trident\/(\S+)/,H=G.exec(navigator.userAgent)))H=parseFloat(H[1]),NaN!=H&&(5<=H?C="9.0":4<=H&&(C="8.0"));var I={product:A,platform:navigator.platform,version:C};window.highedweb.userAgent=I;
function B(b,a){for(var c=0,d=b.replace(/(^\s*|\s*$)/g,"").split("."),e=a.replace(/(^\s*|\s*$)/g,"").split("."),f=Math.max(d.length,e.length),t=0;0==c&&t<f;t++){var u=d[t]||"",F=e[t]||"",V=RegExp("(\\d*)(\\D*)","g"),W=RegExp("(\\d*)(\\D*)","g");do{var k=V.exec(u)||["","",""],l=W.exec(F)||["","",""];if(0==k[0].length&&0==l[0].length)break;c=((0==k[1].length?0:parseInt(k[1],10))<(0==l[1].length?0:parseInt(l[1],10))?-1:(0==k[1].length?0:parseInt(k[1],10))>(0==l[1].length?0:parseInt(l[1],10))?1:0)||((0==
k[2].length)<(0==l[2].length)?-1:(0==k[2].length)>(0==l[2].length)?1:0)||(k[2]<l[2]?-1:k[2]>l[2]?1:0)}while(0==c)}return c}window.highedweb.compareVersions=B;var J=window._gaq||[];J.push(["_setAccount","UA-7826679-2"]);J.push(["_trackPageview"]);window._gaq=J;D(("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js",g,i);
w(function(){for(var b=/\.(?:doc|docx|eps|jpg|png|svg|xls|xlsx|ppt|pptx|pdf|zip|txt|vsd|vxd|js|css|rar|exe|wma|mov|avi|wmv|mp3)($|\&|\?)/i,a=document.getElementsByTagName("a"),c=0;c<a.length;c++)try{if(a[c].protocol&&"javascript:"!=a[c].protocol)if("mailto:"==a[c].protocol)j(a[c],"click",function(a){return function(){window._gaq.push(["_trackPageview","/mailto/"+a.substring(7)])}}(a[c]));else if(a[c].hostname==window.location.host){if(b.test(a[c].pathname+a[c].search)){var d=a[c].pathname.replace(/\\|%5C/ig,
"/"),e="/"==d.charAt(0)?d:"/"+d;a[c].search&&-1==d.indexOf(a[c].search)&&(e+=a[c].search);j(a[c],"click",function(a){return function(){window._gaq.push(["_trackPageview",a])}}(e))}}else j(a[c],"click",function(a){return function(){window._gaq.push(["_trackPageview","/external/"+a.host+a.pathname+a.search+a.hash])}}(a[c]))}catch(f){}});var K=0<=I.platform.indexOf("Win")&&!I.product.Opera;
window.highedweb.requireFlashVersion=window.highedweb.detectFlashVersion=function(b){var a;a=-1;if(navigator.plugins!=h&&0<navigator.plugins.length){if(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]){a=navigator.plugins["Shockwave Flash"+(navigator.plugins["Shockwave Flash 2.0"]?" 2.0":"")].description.split(" ");var c=a[2].split("."),d=[],e=c[0],c=c[1],d=""!=a[3]?a[3].split("r"):a[4].split("r");a=e+"."+c+"."+(0<d[1]?d[1]:0)}}else if(K)a:{try{e=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7");
a=d=e.GetVariable("$version");break a}catch(f){}a=-1}if(-1==a)return i;if(0!=a)return K&&(a=a.split(" "),d=a[0],1<a.length&&(d=a[1]),a=d.replace(/,/g,".")),0<=B(a,b)};
window.highedweb.generateFlashObject=function(b){var a=['<object type="application/x-shockwave-flash"'];a.push(' data="',b.movie,'"');b.width&&a.push(' width="',b.width,'"');b.height&&a.push(' height="',b.height,'"');b.id&&a.push(' id="',b.id,'"');b["class"]&&a.push(' class="',b["class"],'"');b.style&&a.push(' style="',b.style,'"');a.push(">\n");for(var c in b)switch(c.toLowerCase()){case "id":case "class":case "width":case "height":case "style":break;default:a.push('<param name="',c,'" value="',
b[c],'"/>\n')}a.push("</object>");document.write(a.join(""))};
if(A.IE&&0>B(C,"9.0")){for(var L="abbr article aside audio canvas details figcaption figure footer header hgroup mark meter nav output progress section summary time video".split(" "),M=L.length,N=RegExp("<(/*)(abbr|article|aside|audio|canvas|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video)","gi"),O=RegExp("(^|[^\\n]*?\\s)(abbr|article|aside|audio|canvas|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video)([^\\n]*)({[\\n\\w\\W]*?})","gi"),
P=RegExp("(^|\\s)(abbr|article|aside|audio|canvas|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video)","gi"),Q=document.createDocumentFragment(),R=document.documentElement,S=document.getElementsByTagName("head"),T=S?S[0]:h,U=document.createElement("style"),X=document.createElement("body"),Y=0;Y<M;Y++)document.createElement(L[Y]),Q.createElement(L[Y]);U.media="all";var Z=function(b,a){for(var c=b.length,d,e=[],f=0;f<c;f++)d=b[f],a=d.media||a,e.push(Z(d.imports,
a)),e.push(d.cssText);return e.join("")};window.attachEvent("onbeforeprint",function(){for(var b,a=[],c,d,e=0;e<M;e++){c=document.getElementsByTagName(L[e]);b=c.length;for(d=0;d<b;d++)0>c[d].className.indexOf("iepp_")&&(c[d].className+=" iepp_"+L[e])}for(c=Z(document.styleSheets,"all");(b=O.exec(c))!=h;)a.push((b[1]+b[2]+b[3]).replace(P,"$1.iepp_$2")+b[4]);T.insertBefore(U,T.firstChild);U.styleSheet.cssText=a.join("\n");Q.appendChild(document.body);R.appendChild(X);X.innerHTML=Q.firstChild.innerHTML.replace(N,
"<$1bdo")});window.attachEvent("onafterprint",function(){R.removeChild(X);X.innerHTML="";T.removeChild(U);R.appendChild(Q.firstChild)})};})()
